### ISSUE TITLE
can't log in at campuscodefest.org with google or meetup auths

### ISSUE THREAD

**Issue by mjhoy** [campuscodefest/ccf#103]
hi,

trying to login with google @ campuscodefest.org gives me a 404. perhaps a CSRF problem? the url is:

`http://campuscodefest.org/auth/failure?message=csrf_detected&strategy=google_oauth2`

Also, meetup loads but says "Invalid authorization request".

**Comment by pete2786** [comment]
That domain should be retired, that is my bad on the documentation. We want everything to go through coeventer.com, so we removed those domains. Need to re-configure the server as well.

**Comment by mjhoy** [comment]
ah whoops!

**Comment by mjhoy** [comment]
@pete2786 i realized how i got here (again), if you google incorrect spelling of "coeventor", which i seem to do, umn.campuscodefest.org is the first hit. (for the correct spelling it's the second hit).

**Comment by pete2786** [comment]
Ah ha, thanks!
