### ISSUE TITLE
users#show: "attendend X events" includes upcoming events

### ISSUE THREAD

**Issue by mjhoy** [campuscodefest/ccf#104]
this made me worried for a second i had somehow missed the upcoming geocode event!
my suggestion would be to break out:

attended X events: applies to registrations linked to past events (end_date < Time.now)

registered for X upcoming events: the opposite of above (end_date > Time.now)

**Comment by pete2786** [comment]
Thanks for the suggestion, made a change.

Reference commit:
993745e3ca548baf6528cab21b0d284edef1dd3b

**Comment by pete2786** [comment]
After getting this out, I took the time to make some general improvements... and ending up doing a different direction. Got a first step towards a more meaningful profile with a tweaked layout and adding an aggregation of ideas...

<img width="1139" alt="screen shot 2016-03-04 at 6 38 15 am" src="https://cloud.githubusercontent.com/assets/1348257/13527292/b4c2f528-e1d3-11e5-9a78-c7185fb3d428.png">

**Comment by mjhoy** [comment]
that's a great improvement. thanks.
