### ISSUE TITLE
comment_posted: every users's notification included in each email?

### ISSUE THREAD

**Issue by mjhoy** [campuscodefest/ccf#105]

**Comment by mjhoy** [comment]
I just commented in a project in geocode, and received a very strange notification, it seemed to be the notification repeated for each user in the thread. Raw email below, notice that there seem to be 3 of each text and html email mime sections. I wonder if it has to do with calling `format` in a loop in the comment mailer? Bug in rails?

```
----==_mimepart_56d76d65508bc_4271c9b36434554
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Nate Kabat,

A new comment has been posted for Regional Bike Facility Application:

I'm definitely interested in the analysis as well. Can't seem to find anything online.

Visit this project: http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application
Disable these emails if you hate them: http://opentwincities.coeventer.com/users/351/edit
----==_mimepart_56d76d65508bc_4271c9b36434554
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Boyd Johnson,

A new comment has been posted for Regional Bike Facility Application:

I'm definitely interested in the analysis as well. Can't seem to find anything online.

Visit this project: http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application
Disable these emails if you hate them: http://opentwincities.coeventer.com/users/352/edit
----==_mimepart_56d76d65508bc_4271c9b36434554
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Michael Hoy,

A new comment has been posted for Regional Bike Facility Application:

I'm definitely interested in the analysis as well. Can't seem to find anything online.

Visit this project: http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application
Disable these emails if you hate them: http://opentwincities.coeventer.com/users/488/edit
----==_mimepart_56d76d65508bc_4271c9b36434554
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Nate Kabat,</p>

    <p>A new comment has been posted for Regional Bike Facility Application:</p>

    <p>I'm definitely interested in the analysis as well. Can't seem to find anything online.<br></p>

    <p><a href="http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application">Visit this project</a></p>
    <p><a href="http://opentwincities.coeventer.com/users/351/edit">Disable these emails</a> if you hate them</p>
</body>
</html>
----==_mimepart_56d76d65508bc_4271c9b36434554
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Boyd Johnson,</p>

    <p>A new comment has been posted for Regional Bike Facility Application:</p>

    <p>I'm definitely interested in the analysis as well. Can't seem to find anything online.<br></p>

    <p><a href="http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application">Visit this project</a></p>
    <p><a href="http://opentwincities.coeventer.com/users/352/edit">Disable these emails</a> if you hate them</p>
</body>
</html>
----==_mimepart_56d76d65508bc_4271c9b36434554
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Michael Hoy,</p>

    <p>A new comment has been posted for Regional Bike Facility Application:</p>

    <p>I'm definitely interested in the analysis as well. Can't seem to find anything online.<br></p>

    <p><a href="http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application">Visit this project</a></p>
    <p><a href="http://opentwincities.coeventer.com/users/488/edit">Disable these emails</a> if you hate them</p>
</body>
</html>
----==_mimepart_56d76d65508bc_4271c9b36434554--
```

**Comment by pete2786** [comment]
Thanks will look tonight
On Wed, Mar 2, 2016 at 17:47 Michael Hoy <notifications@github.com> wrote:

> I just commented in a project in geocode, and received a very strange
> notification, it seemed to be the notification repeated for each user in
> the thread. Raw email below, notice that there seem to be 3 of each text
> and html email mime sections. I wonder if it has to do with calling format
> in a loop in the comment mailer? Bug in rails?
>
> ----==_mimepart_56d76d65508bc_4271c9b36434554
> Content-Type: text/plain;
>  charset=UTF-8
> Content-Transfer-Encoding: 7bit
>
> Nate Kabat,
>
> A new comment has been posted for Regional Bike Facility Application:
>
> I'm definitely interested in the analysis as well. Can't seem to find anything online.
>
> Visit this project: http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application
> Disable these emails if you hate them: http://opentwincities.coeventer.com/users/351/edit
> ----==_mimepart_56d76d65508bc_4271c9b36434554
> Content-Type: text/plain;
>  charset=UTF-8
> Content-Transfer-Encoding: 7bit
>
> Boyd Johnson,
>
> A new comment has been posted for Regional Bike Facility Application:
>
> I'm definitely interested in the analysis as well. Can't seem to find anything online.
>
> Visit this project: http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application
> Disable these emails if you hate them: http://opentwincities.coeventer.com/users/352/edit
> ----==_mimepart_56d76d65508bc_4271c9b36434554
> Content-Type: text/plain;
>  charset=UTF-8
> Content-Transfer-Encoding: 7bit
>
> Michael Hoy,
>
> A new comment has been posted for Regional Bike Facility Application:
>
> I'm definitely interested in the analysis as well. Can't seem to find anything online.
>
> Visit this project: http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application
> Disable these emails if you hate them: http://opentwincities.coeventer.com/users/488/edit
> ----==_mimepart_56d76d65508bc_4271c9b36434554
> Content-Type: text/html;
>  charset=UTF-8
> Content-Transfer-Encoding: 7bit
>
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
>   </head>
>   <body>
>     <p>Nate Kabat,</p>
>
>     <p>A new comment has been posted for Regional Bike Facility Application:</p>
>
>     <p>I'm definitely interested in the analysis as well. Can't seem to find anything online.<br></p>
>
>     <p><a href="http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application">Visit this project</a></p>
>     <p><a href="http://opentwincities.coeventer.com/users/351/edit">Disable these emails</a> if you hate them</p>
> </body>
> </html>
> ----==_mimepart_56d76d65508bc_4271c9b36434554
> Content-Type: text/html;
>  charset=UTF-8
> Content-Transfer-Encoding: 7bit
>
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
>   </head>
>   <body>
>     <p>Boyd Johnson,</p>
>
>     <p>A new comment has been posted for Regional Bike Facility Application:</p>
>
>     <p>I'm definitely interested in the analysis as well. Can't seem to find anything online.<br></p>
>
>     <p><a href="http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application">Visit this project</a></p>
>     <p><a href="http://opentwincities.coeventer.com/users/352/edit">Disable these emails</a> if you hate them</p>
> </body>
> </html>
> ----==_mimepart_56d76d65508bc_4271c9b36434554
> Content-Type: text/html;
>  charset=UTF-8
> Content-Transfer-Encoding: 7bit
>
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
>   </head>
>   <body>
>     <p>Michael Hoy,</p>
>
>     <p>A new comment has been posted for Regional Bike Facility Application:</p>
>
>     <p>I'm definitely interested in the analysis as well. Can't seem to find anything online.<br></p>
>
>     <p><a href="http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application">Visit this project</a></p>
>     <p><a href="http://opentwincities.coeventer.com/users/488/edit">Disable these emails</a> if you hate them</p>
> </body>
> </html>
> ----==_mimepart_56d76d65508bc_4271c9b36434554--
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/campuscodefest/ccf/issues/105#issuecomment-191497702>.
>
-- 
*David Peterson*
SOFTWARE ENGINEER

Sport Ngin | 1400 Van Buren St NE | Minneapolis, MN 55413
sportngin.com | twitter.com/sportngin | facebook.com/sportngin

**Comment by mjhoy** [comment]
here is where i posted the comment, btw http://opentwincities.coeventer.com/projects/113-regional-bike-facility-application

**Comment by pete2786** [comment]
Rails 4 upgrade bug strike again... Fixing

**Comment by pete2786** [comment]
Yep, your suspicion was correct. This worked in Rails 3 but the syntax changed in Rails 4 for the Mailers. 

Reference commit:
bc2a66b0fb480465726ff8b00402779910a50a89
