### ISSUE TITLE
Departments?

### ISSUE THREAD

**Issue by maxfierke** [campuscodefest/ccf#60]
I'm noticing that `User#department` is excluded from being saved, despite being an editable field in the profile edit view. There's also a `deptid` column in the `users` table but doesn't appear to be used anywhere.

What's the story on this? Looks like a foot in, foot out kind of situation.

**Comment by pete2786** [comment]
Two half baked features. I'd guess it was simply mistakenly excluded. It is not shown anywhere at the moment, think it was mostly for "cross sectional" reporting.

**Comment by pete2786** [comment]
Removed from user edit for now
