### ISSUE TITLE
Bug: NoMethodError during event creation when viewing <event>/builder/registration

### ISSUE THREAD

**Issue by wbushey** [campuscodefest/ccf#82]
When running master locally, if I attempt to create an event for for an organization, I encounter a 500 - NoMethodError when I hit submit and the wizard tries to go to <event>/builder/registration . It looks like the event model tries to call in_time_zone on a date field that is nil at the moment (since the user hasn't yet gotten to enter it).

**Comment by pete2786** [comment]
Hmm, I thought it should default you to CST, I will take a look. Thanks.

**Comment by pete2786** [comment]
Weird how that did not happen on the first view... anyways thanks for fixing, I just tested it locally and deployed.
