### ISSUE TITLE
Bug: NoMethodError when clicking "Register Now" for event

### ISSUE THREAD

**Issue by wbushey** [campuscodefest/ccf#83]
When viewing an event on localhost on master, if I click the "Register Now" button, I get a 500 - NoMethodError: undefined method `organization_id=' for #\<EventRegistration>.

**Comment by wbushey** [comment]
For those interested in the traceback: http://pastebin.com/HabeWkux

**Comment by pete2786** [comment]
Were you using an [org_subdomain].lvh.me:3000 domain?

**Comment by pete2786** [comment]
Also, were you logged in? I think the issue might be returning from OAuth not properly pulling the organization id.

**Comment by wbushey** [comment]
Yup, I'm using an org subdomain, and am logged in. After digging around a bit, it seems to me that for some reason, Cancan is trying to assign an organization_id to an EventRegistration.

**Comment by wbushey** [comment]
Huh, I logged out, then logged back in, and now it works fine...

Sorry about that. Feel free to close this.

**Comment by pete2786** [comment]
Sounds good, thanks for double checking.
