### ISSUE TITLE
Fun w/Time zones

### ISSUE THREAD

**Issue by pete2786** [campuscodefest/ccf#89]
Looking at the time zone conversions, looks like things we slightly weird when creating the GeoCode event. It appears as the intent was to have the event start at 9am but it is either displaying in UTC or may have been improperly converted to 3am (which is CST-6). This is a new but essential feature to get right.

![image](https://cloud.githubusercontent.com/assets/1348257/12177126/3d863634-b530-11e5-857d-92fcdc8acda1.png)

@wbushey Could you confirm this is an issue?

**Comment by pete2786** [comment]
Ah, the issue is editing an event versus creating the event, will fix ASAP.

**Comment by pete2786** [comment]
Found the problem and deployed the fix. It was one of the fun issues which worked locally for me but not on the server. There were some inconsistencies converting the time, so I made it more implicit.

https://github.com/campuscodefest/ccf/commit/6a8b6b2f757891d69d8a448aca46960b28bb67c5

@wbushey You may want to review the event configured times for GeoCode on the site.

**Comment by wbushey** [comment]
Thanks @pete2786 for catching this. I'd seen this happen when creating/editing the event, but forgot to report the bug. Glad you saw it and took care of it.
