### ISSUE TITLE
When creating an account, bring the user back to the page they began account creation at

### ISSUE THREAD

**Issue by wbushey** [campuscodefest/ccf#90]
Passing along some feedback from a user who creating an account via Meetup (which requires the email entry/confirmation step). Right now, when the user clicks the confirmation link in the email sent to them, they will be taken to the homepage of coeventer.com. The user suggests that a smoother experience would be, upon the user clicking the email confirmation link, to take the user to the page where they started logging in/creating an account (which could be event RSVPing, joining an org, etc...).

**Comment by pete2786** [comment]
Sounds good, I'll try and think of a better solution. Adding multiple providers broke up our previous flow which was pretty good.

**Comment by pete2786** [comment]
This gets us at least back where we came from. We still need a little more thought to handle if the click was an actionable link.

https://github.com/campuscodefest/ccf/pull/93

**Comment by wbushey** [comment]
I totally missed that you took care of this. Thanks :+1:
