### ISSUE TITLE
Change content of the registration email

### ISSUE THREAD

**Issue by wbushey** [campuscodefest/ccf#91]
Some more user feedback, this time about the email that gets sent when somebody registers for an event. Specifically for Geo:Code, we're focusing on creating a welcoming event for a wide audience, including many non-technologists who might feel less welcomed when they see they should have a basic understanding of git. So, I'm thinking of changing the content of that email.

In the short term, I can easily change the mailer templates to better fit Geo:Code. In the long term, what does everybody think about being able to customize the registration email for an event?

**Comment by pete2786** [comment]
Yes, absolutely something we need to do going forward. I am OK with a quick fix. If you need to get something deployed quickly, let me know.

It may be just as easy to add some better default content AND add a column to the event model (or something) to hold custom registration email text.

**Comment by wbushey** [comment]
Cool, I'll send a PR shortly with an updated registration confirmation email (and one that is still hopefully pretty general). And yea, I'd definitely appreciate a quick deploy, since we've already started to promote the event.

For the longer term, are you suggesting that the registration_created mailer would have some stock content, then include (say) ```@event.registration_email```?

**Comment by pete2786** [comment]
Something like that. Now that I think about it, we should consider a different data model versus tacking more on event. There are quite a few options text blocks. Probably needs to be abstracted out. 

Some day... Thanks for the PR, the copy is a great improvement.
