### ISSUE TITLE
constant already initialized warning

### ISSUE THREAD

**Issue by mjhoy** [campuscodefest/ccf#99]
in development I get `warning: already initialized constant OpenSSL::SSL::VERIFY_PEER` as a result of this line: https://github.com/campuscodefest/ccf/blob/master/config/initializers/omniauth.rb#L5

it can be fixed by first un-defining the constant: https://github.com/mjhoy/ccf/commit/3ed39f96f8446ae3a9bba9fba0d7ee6c104b00ce (i can submit as PR if you want)

but i also wonder why this line exists in development? seems potentially dangerous to turn off ssl verification?

thanks.

**Comment by pete2786** [comment]
It is an issue running the app on some versions of Mac OS X. I don't think there are any security risks locally.

**Comment by mjhoy** [comment]
ah, ok. submitted a pr for the warning.
